Repository universi-me/universi-api, pull requests merged in 2022-10, with the labels that each got.

#13 [adrian.fernandes] CHANGE#12 alteracao da nomenclatura de ingles para…
  src/main/java/me/universi/usuario/entities/Usuario.java
Labels: change

#23 feat#17: Criação de entidade Link e enum TipoLink
  src/main/java/me/universi/link/entities/Link.java
  src/main/java/me/universi/link/entities/TipoLink.java
Labels: enhancement, feature

#26 fix#25: Alteração mapeamento entre Perfil e Link
  src/main/java/me/universi/link/entities/Link.java
  src/main/java/me/universi/link/enums/TipoLink.java
  src/main/java/me/universi/perfil/entities/Perfil.java
Labels: change

#27 feat#14: Adicionando atributos em Perfil
  src/main/java/me/universi/link/entities/Link.java
  src/main/java/me/universi/perfil/entities/Perfil.java
  src/main/java/me/universi/perfil/enums/Sexo.java
Labels: enhancement, feature

#30 feat#18: Criação entidade recomendação
  src/main/java/me/universi/perfil/entities/Perfil.java
  src/main/java/me/universi/recomendacao/entities/Recomendacao.java
Labels: feature

#37 fix#32: Alteração mapeamento Perfil/Link
  src/main/java/me/universi/perfil/entities/Perfil.java
Labels: bug, change

#68 FEAT#56: Criacao de CRUD Competencia
  src/main/java/me/universi/competencia/controller/CompetenciaController.java
  src/main/java/me/universi/competencia/entities/Competencia.java
Labels: enhancement, feature

#67 BUG#36: Alteração String mapeamento
  src/main/java/me/universi/perfil/entities/Perfil.java
Labels: bug, change

#81 FEAT#80: Criar construtor vazio do Perfil
  src/main/java/me/universi/perfil/entities/Perfil.java
Labels: feature

#85 Feat#84/criacao recomendacao controller
  src/main/java/me/universi/recomendacao/controller/RecomendacaoController.java
  src/main/java/me/universi/recomendacao/entities/Recomendacao.java
  src/main/java/me/universi/recomendacao/repositories/RecomendacaoRepository.java
Labels: enhancement, feature

#83 FEAT#82: Criação CRUD Recomendação
  src/main/java/me/universi/recomendacao/entities/Recomendacao.java
  src/main/java/me/universi/recomendacao/repositories/RecomendacaoRepository.java
Labels: enhancement, feature

#88 FEAT#86: Criação do RecomendacaoService
  src/main/java/me/universi/recomendacao/controller/RecomendacaoController.java
  src/main/java/me/universi/recomendacao/service/RecomendacaoService.java
Labels: enhancement, feature
