Repository universi-me/universi-api, pull requests merged in 2022-11, with the labels that each got.

#90 CHANGE#89: Alteração na nomeclatura do mapeamento
  src/main/java/me/universi/recomendacao/entities/Recomendacao.java
Labels: change

#92 FEAT#91: Implementando validações com RecomendacaoInvalidaException n…
  src/main/java/me/universi/recomendacao/controller/RecomendacaoController.java
  src/main/java/me/universi/recomendacao/exceptions/RecomendacaoInvalidaException.java
  src/main/java/me/universi/recomendacao/service/RecomendacaoService.java
Labels: enhancement, feature

#208 FEAT#207: Editar dados do perfil
  src/main/java/me/universi/perfil/controller/PerfilController.java
  src/main/java/me/universi/perfil/services/PerfilService.java
Labels: feature

#214 CHANGE#212: Salvar dados do perfil e usuário
  src/main/java/me/universi/perfil/controller/PerfilController.java
Labels: change

#215 FEAT#163: Implementando entidade PerfilService já criada
  src/main/java/me/universi/perfil/services/PerfilService.java
Labels: change

#216 FEAT#164: Criação da entidade PerfilException
  src/main/java/me/universi/perfil/exceptions/PerfilException.java
Labels: feature

#226 FEAT#255: Criação de classes de teste e implementando teste Perfil
  src/main/java/me/universi/perfil/services/PerfilService.java
  src/test/java/me/universi/CompetenciaTest.java
  src/test/java/me/universi/PerfilTest.java
  src/test/java/me/universi/RecomendacaoTest.java
Labels: feature
